FROM node:12.2.0-alpine

WORKDIR /online_shop_vue
ENV PATH /online_shop_vue/node_modules/.bin:$PATH

COPY package.json /online_shop_vue/package.json
RUN npm install
RUN npm install @vue/cli@3.7.0 -g

CMD ["npm", "run", "serve"]
